# Generated by Django 3.1.5 on 2021-03-16 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/')),
                ('image_converted', models.ImageField(blank=True, null=True, upload_to='article/converted/')),
                ('style', models.CharField(blank=True, choices=[('NO_FILTER', '원본 사진'), ('HAYAO', 'HAYAO 화풍'), ('HOSODA', 'HOSODA 화풍'), ('SHINKAI', 'SHINKAI 화풍'), ('PAPRIKA', 'PAPRIKA 화풍')], max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='projectapp.project')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
