# Generated by Django 3.1.5 on 2021-02-16 08:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NO_FILTER', '원본 사진을 이모티콘으로 만들기'), ('HAYAO', 'HAYAO 화풍으로 이모티콘 만들기'), ('HOSODA', 'HOSODA 화풍으로 이모티콘 만들기'), ('SHINKAI', 'SHINKAI 화풍으로 이모티콘 만들기'), ('PAPRIKA', 'PAPRIKA 화풍으로 이모티콘 만들기')], default='', max_length=38),
        ),
    ]
