# Generated by Django 3.1.5 on 2021-02-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_converted',
            field=models.ImageField(null=True, upload_to='article/converted/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='style',
            field=models.CharField(blank=True, choices=[('NO_FILTER', '원본 사진'), ('HAYAO', 'HAYAO 화풍'), ('HOSODA', 'HOSODA 화풍'), ('SHINKAI', 'SHINKAI 화풍'), ('PAPRIKA', 'PAPRIKA 화풍')], max_length=50, null=True),
        ),
    ]
