# Generated by Django 3.1.5 on 2021-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_article_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_converted',
            field=models.ImageField(blank=True, null=True, upload_to='article/converted/'),
        ),
    ]
